### ISSUE TITLE
Too much time for loading image feature

### ISSUE THREAD

**Issue by vanpersie32** [JonghwanMun/TextguidedATT#8]
Hi, I have noticed that  too much time has been spent on feature loading, because of each t7 file record feature map of an image. I recommend using hdf5 file to record the feature in feature extraction

![image](https://user-images.githubusercontent.com/15981416/35398111-2269b8f8-022c-11e8-9f48-8b2e2fec2f60.png)

**Comment by vanpersie32** [comment]
The reason why feature extraction is so slow is because you collect garbage too often. Here Here Here [https://github.com/JonghwanMun/TextguidedATT/issues/8](url)

**Comment by JonghwanMun** [comment]
I tried to use both data types, t7 and hdf5, and there was no difference in extraction time for me.

**Comment by vanpersie32** [comment]
@JonghwanMun  yeah, I have notice that too. There is no much difference between reading h5 and t7 file. But how do we solve the problem, the gpu utils is very slow due to the fact that much time has been spent on data reading

**Comment by JonghwanMun** [comment]
@vanpersie32 Using multi-thread or multi-process is one possible solution on data loading. But, for me, it was difficult to use multi-thread in lua.

**Comment by vanpersie32** [comment]
@JonghwanMun Thank you for your advice, really appreciate it.
